exclude: '((data|preprocessed_data|public)/.*)|(.*\.(csv|tsv))$|(.*logfile.*)'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files  # max 500kb files
      - id: check-merge-conflict
      - id: check-toml
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.2
    hooks:
      - id: nbstripout
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      # Run the formatter.
      - id: ruff-format
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
  - repo: local
    hooks:
      - id: update-version
        name: Update package version in CITATION.cff and docs/conf.py
        entry: >
          sh -c 'if command -v pwsh >/dev/null 2>&1 || [ "$0" = "pwsh" ]; then
              echo "Skipping in PowerShell";
          else
              os_type=$(uname) &&
              if [ "$os_type" = "Darwin" ]; then
                  version=$(awk -F "\"" "/version =/ {print \$2}" pyproject.toml) &&
                  sed -i "" "s/^version: .*/version: $version/" CITATION.cff &&
                  sed -i "" "s/^version = .*/version = \"$version\"/" docs/conf.py &&
                  sed -i "" "s/^release = .*/release = \"$version\"/" docs/conf.py;
              elif [ "$os_type" = "Linux" ]; then
                  version=$(grep -oP "(?<=version = \")[^\"]+" pyproject.toml) &&
                  sed -i "s/^version: .*/version: $version/" CITATION.cff &&
                  sed -i "s/^version = .*/version = \"$version\"/" docs/conf.py &&
                  sed -i "s/^release = .*/release = \"$version\"/" docs/conf.py;
              else
                  echo "Unsupported OS type: $os_type";
                  exit 1;
              fi
          fi'
        language: system
        files: 'CITATION\.cff|pyproject\.toml|docs/conf\.py'
        pass_filenames: false
