data_collection_name: "MultiplEYE_ZH_CH_Zurich_1_2025"
experiment_type: "MeRID" # can be either MultiplEYE or MeRID

overwrite: False # defines whether written files will be overwritten, if they already exist. If False, preprocessed sessions will be skipped and not reprocessed.
                # If only some files for a session exist, the user has to select overwrite once to avoid having files stemming from different versions.


# SESSIONS
## pick either include or exclude sessions, if none is specified, all sessions are included
include_sessions:
  - 089_ZH_CH_1_ET1
exclude_sessions:
  #- 021_DA_DK_1_ET1

include_pilots: False

# HARDWARE
expected_sampling_rate_hz: 1000  # Hz

# PREPROCESSING
## stimuli
custom_uoas: False
