data_collection_name: "MultiplEYE_IT_CH_Lugano_1_2026"

overwrite: False # defines whether written files will be overwritten, if they already exist. If False, preprocessed sessions will be skipped and not reprocessed.
                # If only some files for a session exist, the user has to select overwrite once to avoid having files stemming from different versions.


# SESSIONS
## pick either include or exclude sessions, if none is specified, all sessions are included
include_sessions:
exclude_sessions:

include_pilots: True

# HARDWARE
expected_sampling_rate_hz: 1000  # Hz

# PREPROCESSING
## stimuli
custom_uoas: False
